branches:
    only:
        - master
git:
    depth: 10

language: cpp

os: osx

env:
    - ATOM_CHANNEL=stable
      NODE_REDIRECT_WARNINGS=/dev/null

    - ATOM_CHANNEL=beta
      NODE_REDIRECT_WARNINGS=/dev/null

notifications:
    email:
        on_success: never
        on_failure: change

script: curl -sL https://git.io/fji1w | sh
