branches:
    only:
        - master
git:
    depth: 10

language: cpp

os: osx

env:
    - ATOM_CHANNEL=stable
    - ATOM_CHANNEL=beta

notifications:
    email:
        on_success: never
        on_failure: change

script: |
    export NODE_REDIRECT_WARNINGS=/dev/null
    curl -sL https://git.io/fji1w | sh
