branches:
    only:
        - master
git:
    depth: 10

language: node_js

node_js: 12

os: osx

env:
    - ATOM_CHANNEL=stable
    - ATOM_CHANNEL=beta

notifications:
    email:
        on_success: never
        on_failure: change

script: curl -sL https://git.io/fji1w | sh
